apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server-srv27
  namespace: iperf3-test
  labels:
    app: iperf3-server
spec:
  nodeSelector:
    kubernetes.io/hostname: nvd-srv-27.nvidia.eng.rdu2.dc.redhat.com
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    args: ["-s"]  # Server mode
    ports:
    - containerPort: 5201
      protocol: TCP
