apiVersion: v1
kind: Pod
metadata:
  name: nginx-server-srv27
  namespace: iperf3-test
  labels:
    app: nginx-server
spec:
  nodeSelector:
    kubernetes.io/hostname: nvd-srv-27.nvidia.eng.rdu2.dc.redhat.com
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
