apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-udn
  namespace: iperf3-test
  labels:
    app: test-vm
  annotations:
    kubevirt.io/allow-pod-bridge-network-live-migration: "true"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm-udn
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: nvd-srv-23.nvidia.eng.rdu2.dc.redhat.com
      domain:
        devices:
          autoattachSerialConsole: true
          interfaces:
            - name: default
              bridge: {}
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 1Gi
            cpu: "1"
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
              bootcmd:
                - [ sh, -c, 'grubby --update-kernel=ALL --args="console=tty0 console=ttyS0,115200n8"' ]
              runcmd:
                - systemctl enable serial-getty@ttyS0.service
                - systemctl start serial-getty@ttyS0.service
