apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-udn-srv27
  namespace: my-ns-udn
  labels:
    app: test-vm
  annotations:
    kubevirt.io/allow-pod-bridge-network-live-migration: "true"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm-udn-srv27
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: nvd-srv-27.nvidia.eng.rdu2.dc.redhat.com
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 1Gi
            cpu: "1"
            openshift.io/bf3-p0-vfs: "2"
          limits:
            openshift.io/bf3-p0-vfs: "2"
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
